/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/portweaver/golibs */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 5 "ddns.go"
 #include <stdlib.h>
 #include <string.h>

#line 1 "cgo-generated-wrapper"

#line 5 "frp.go"
 #include <stdlib.h>
 #include <string.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void DdnsInit(void);
extern int DdnsCreateInstance(char* dnsProvider);
extern int DdnsSetProviderName(int instanceID, char* providerName);
extern int DdnsSetCredentials(int instanceID, char* id, char* secret);
extern int DdnsSetExtParam(int instanceID, char* extParam);
extern int DdnsAddDomain(int instanceID, char* domainName, char* subDomain, int ipv4Enabled, int ipv6Enabled);
extern int DdnsRemoveDomain(int instanceID, char* domainName, char* subDomain);
extern int DdnsClearDomains(int instanceID);
extern int DdnsSetIPv4Address(int instanceID, char* ipv4Addr);
extern int DdnsSetIPv4GetType(int instanceID, char* getType);
extern int DdnsSetIPv6Address(int instanceID, char* ipv6Addr);
extern int DdnsSetIPv6GetType(int instanceID, char* getType);
extern int DdnsUpdateOnce(int instanceID);
extern int DdnsStartAutoUpdate(int instanceID, int intervalSeconds);
extern int DdnsStopAutoUpdate(int instanceID);
extern int DdnsDestroyInstance(int instanceID);
extern void DdnsFreeString(char* str);
extern char* DdnsGetStatusAndLogs(int instanceID);
extern void DdnsClearLogs(int instanceID);
extern void DdnsCleanup(void);
extern void FrpInit(void);
extern int FrpCreateClient(char* serverAddr, int serverPort, char* token, char* logLevel, char* clientName);
extern int FrpAddTcpProxy(int clientID, char* proxyName, char* localIP, int localPort, int remotePort);
extern int FrpAddUdpProxy(int clientID, char* proxyName, char* localIP, int localPort, int remotePort);
extern int FrpFlushClient(int clientID);
extern int FrpStartClient(int clientID);
extern int FrpStopClient(int clientID);
extern int FrpDestroyClient(int clientID);
extern char* FrpGetVersion(void);
extern void FrpFreeString(char* str);
extern char* FrpGetStatus(int clientID);
extern char* FrpGetLogs(int clientID);
extern void FrpClearLogs(int clientID);
extern void FrpCleanup(void);

#ifdef __cplusplus
}
#endif
